name: main

on:
  push:
  pull_request:
  schedule:
    - cron: '48 10 * * 6'

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: kn version
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
